### ISSUE TITLE
PGAP on Singularity 2.5.2

### ISSUE THREAD

**Issue by junkim83** [ncbi/pgap#100] opened 2020-09-04 10:24 UTC
Hello PGAP developer.

Since I'm using the sever on my Institute, I'm using singularity rather than docker for the sudo issue. 

I ran the "./PGAP -D singularity --update" on the singularity 2.5.2, and it worked (updated and downloaded test_genome)

So, I think that it's not a problem with singularity.

But for the test annotation, I ran the PGAP with command  "./pgap.py -D singularity -r -o ......"

It gave me an error with the message which means that there is no '-v' option for "singularity run"

'
ERROR: Unknown option: -v
Command '['/opt/singularity/2.5.2/bin/singularity', 'run', '-i', '-v', '/scratch/r798a01/data_analysis/Annotation:/cwd', 'ncbi/pgap:2020-07-09.build4716', 'bash', '-c', 'df -k /cwd /tmp ; ulimit -a ; cat /proc/{meminfo,cpuinfo}']' returned non-zero exit status 1."
'

I checked the code on pgap.py and found that below

'
 if (self.params.docker_type == 'singularity'):
            cmd = [self.params.docker_cmd, 'exec', '--bind', '{}:/cwd:ro'.format(os.getcwd()), "docker://"+self.params.docker_image,
                   'bash', '-c', 'df -k /cwd /tmp ; ulimit -a ; cat /proc/{meminfo,cpuinfo}']
        else:
            cmd = [self.params.docker_cmd, 'run', '-i', '-v', '{}:/cwd'.format(os.getcwd()), self.params.docker_image,
                   'bash', '-c', 'df -k /cwd /tmp ; ulimit -a ; cat /proc/{meminfo,cpuinfo}']
'

there is -v option on the code. I have no idea for the computer code. 
But, if it might the problem causing the error, is there any way to solve this?

Best,
Jun

**Comment by azat-badretdin** [comment] 2020-09-04 11:31
Thank you for your report! We will process this issue in this Sprint: opened internal ticket PGAPX-844

**Comment by whlavina** [comment] 2020-09-04 12:17
This is likely a duplicate of a problem identified in issue #95 and for which we already have a fix, but it is not yet released.

To confirm it is the same issue, we need the exact output from `singularity --version`. Can you please provide it?

If you can't wait for the next release, try to follow the temporary fix suggested in that issue, edit `pgap.py` around line 577, just before the WARNING line, to force selection of `singularity` instead of `docker` (make the code match the excerpt below). If your issue isn't an exact duplicate, you may have to make a slightly different fix in `get_docker_info()`.

```
            self.docker_type = 'singularity'
            print('WARNING: {} support as Docker alternative has not been tested'.format(docker_alternative))
```

Then run:
```
./pgap.py --no-self-update -D singularity ...
```

**Closed** 2020-09-04 12:50 UTC
Labels: PGAPX-844
