### ISSUE TITLE
no results

### ISSUE THREAD

**Issue by kdyoung100** [ncbi/pgap#231] opened 2022-11-29 02:21 UTC
- pgap.py --version, or docker image version. PGAP version 2022-10-03.build6384 is up to date.

PGAP version 2022-10-03.build6384 is up to date.

commend ./pgap.py -r -o result /data1/tools/pgap/test_genomes-2022-10-03.build6384/MG37/input.yaml 

i don't know error 

please tell me how to fix the error

[cwltool.log](https://github.com/ncbi/pgap/files/10109169/cwltool.log)

**Comment by azat-badretdin** [comment] 2022-11-29 10:06
Thank you, user @kdyoung100 for your report, this is an unfortunate problem related to a third party operations problem, which we are going to fix in the next release. For now the workaround is to remove "publications:" line from `submol.yaml` input file for your example. 

This issue is a duplicate of #230

**Closed by azat-badretdin** 2022-11-29 10:06 UTC

**Comment by azat-badretdin** [comment] 2022-11-29 16:39
> For now the workaround is to remove "publications:" line from submol.yaml input file for your example.

I have added a somewhat simpler workaround option by modifying, temporarily, out test case to eliminate aforementioned publications: section, so you can, if you want, wipe out existing installation and reinstall PGAPx with new test data....
