### ISSUE TITLE
pgap under WSL 2

### ISSUE THREAD

**Issue by nclaesnacw** [ncbi/pgap#127] opened 2021-02-16 14:54 UTC
Hi
Thanks for pgap :-), has anyone managed to run pgap with WSL 2
(latest win10 version 1909 build 18363.1379 and windows Docker desktop installed)

Failed for me on MG37 with:
execing: /pgap/output/debug/tmpdir/s0j99zsb/stgadcea4c5-ab81-4e0a-ae7d-fc2f3b3b5f6c/GeneMark/API_2.2/gmsn.pl --prok --ncbi --gcode 4 --ext genemark-input.gff --incomplete_at_gaps 10 fasta.fna
error, unexpected format foundin file: itr_0.lstterminate called after throwing an instance of 'ncbi::CException'
  what():  NCBI C++ Exception:
    Error: GENEMARK(CException::eUnknown) "../../../../../../../ncbi_cxx/src/internal/gpipe/app/bacterial_pipeline/genem

There do seem to be quite a few gotcha's in WSL  :-(

**Comment by azat-badretdin** [comment] 2021-02-16 16:52
Thanks for your report. This issue seem to be quite similar to #104 

Same host type (windows), same failure in the same binary. I am going to resolve this as a duplicate of #104

**Closed by azat-badretdin** 2021-02-16 16:52 UTC
Labels: PGAPX-893

**Comment by nclaesnacw** [comment] 2021-02-16 17:39
Hi Azat (hope that’s ok)
Thank you, I saw #104 but didn’t connect it or follow the thread. I think WSL should be a better solution to running pgap in windows than running windows docker with linux support – but I accept the just run linux argument – I just lose easy switching for Office and I like geneious and Rstudio better in Windows and textpad as powerful easy to use big file text editor etc
And I accept you prioritizing the linux development – faster with –cpus working might get me back on my 16Gb linux machine 😊 for our 8-10Mb actino genomes.
Thanks
Alan Ward

**Comment by azat-badretdin** [comment] 2021-02-16 19:00
Terminological help for wider audience: **WSL**  = **Windows Subsystem for Linux**

**Comment by azat-badretdin** [comment] 2021-02-16 19:03
As for using WSL vs native Windows 10 - currently, we do not have either in our testing. In terms of diversity of machine types we are limited to testing on Centos-based machines on AWS and GCP. 

Occasionally and out of curiosity some of our team members run tests on their home Macs, but that's it. No regular testing for now on Windows platforms...
