### ISSUE TITLE
Bug if fasta and output folder names are identical

### ISSUE THREAD

**Issue by MyProgramWorks** [ncbi/pgap#63] opened 2020-02-25 16:59 UTC
Hi, I've come across a very odd bug. 

This line:
`./pgap.py -r -o ./Kp1264 pgap.yaml`
gives an error:

> PGAP version 2020-02-06.build4373 is up to date.
> invalid literal for int() with base 10: 'fasta'

but this line (note the A after Kp):
`./pgap.py -r -o ./Kpa1264 pgap.yaml`
doesn't give an error. 

The two commands were tested one right after the other without any changes in any of the input files. 

I think this is caused by the identical name of the output folder Kp1264 and fasta file Kp1264.fasta.

I hope this might save users some time until the bug is fixed.

**Comment by slottad** [comment] 2020-02-25 18:46
Hmm. There is not quite enough info to tell what is going on, since I can't see the contents of your directory nor of your pgap.yaml file. The fasta suffix/output folder thing doesn't make sense, and I suspect there is something else going on here.

Do you think you could recreate this problem with instructions starting from a fresh installation?

**Comment by tseemann** [comment] 2020-02-25 21:22
@MyProgramWorks are you able to paste the contents, or attach, your `pgap.yaml` file?
or, if you've resolved this issue, please close it.

**Comment by jdmanthey** [comment] 2020-03-04 17:31
I had the same issue. If the output directory = test, and the genome name = test.fasta, you get an error: invalid literal for int() with base 10: 'fasta'

If you change the name of the output directory, the program works.

**Comment by whlavina** [comment] 2020-05-22 02:03
I'm sorry, but I cannot reproduce. Besides your command line, can you please include the output of the following?
```
./pgap.py --version
ls -al .
cat pgap.yaml
md5sum pgap.py
```

**Comment by whlavina** [comment] 2020-05-22 02:06
Nevermind; I can reproduce. The issue is overwriting an _existing_ directory, such as if you try to run the same command line twice. This should be an easy fix.

**Comment by MyProgramWorks** [comment] 2020-05-22 11:05
Hi Wratko, my apologies for not providing  a more detailed reproduction example. Thanks for finding the source of the error.

**Comment by whlavina** [comment] 2020-05-22 14:59
We have a fix in dev; we plan to roll it out soon, in the next upcoming release. I'm closing this issue. I'm sorry it took longer to diagnose, since the bug involved 2 conditions, same name + rerun.

**Closed by whlavina** 2020-05-22 14:59 UTC
Labels: PGAPX-777
