### ISSUE TITLE
[BUG] <PGAP version 2020-03-30.build4489 docker exited with rc = 1 Unable to find error in log file.>

### ISSUE THREAD

**Issue by maojn** [ncbi/pgap#69] opened 2020-04-08 21:13 UTC
Hi,
Thank you for offering the singularity version of pgap. It's good for running on cluster.
A user of ours tried it and run into error today. Would you please help?

$ module load singularity
$ singularity version
3.5.3

$ ./pgap.py --update -D singularity
This pull down pgap_2020-03-30.build4489.sif and test files

$ ./pgap.py -D singularity -o MG37_results test_genomes-2020-03-30.build4489/MG37/input.yaml
    
    And I got the following error message:
    
    PGAP version 2020-03-30.build4489 is up to date.
    Output will be placed in: /gpfs/gsfs6/users/launayap/software/MG37_results.1
    WARNING: open files is less than the recommended value of 8000 PGAP failed
    docker exited with rc = 1 
    Unable to find error in log file.

Attached is the log file after adding '-r' 
[cwltool.log](https://github.com/ncbi/pgap/files/4452850/cwltool.log)

**Comment by azat-badretdin** [comment] 2020-04-08 22:11
>open files is less than the recommended value of 8000 

Try `ulimit -n 8192`

**Comment by maojn** [comment] 2020-04-09 15:14
Thank you fro your reply. I have fixed the ulimit error. But the other errors were still exist. Please see the log attached. Thank you.
[cwltool.log](https://github.com/ncbi/pgap/files/4457013/cwltool.log)

**Comment by azat-badretdin** [comment] 2020-04-09 16:25
Thanks. The error is: 
```
Error: (302.22) SSOCK#1000[?]@:443: [SOCK::Connect]  Failed SOCK_gethostbyname("www.ncbi.nlm.nih.gov")
```
Which indicates that you have connection issues from singularity. We will see what is going on with singularity.

**Comment by maojn** [comment] 2020-04-09 18:18
I run on a node of Biowulf cluster in CIT, NIH. A user ran into problem while testing pgap and I am helping debugging. The node uses proxy setting to connect to internet. I just used --no-internet flag which proceeded much longer but eventually failed. Not sure about the consequence of no connection. I am wondering if the container somehow changed the setting of the environmental variables which caused problem. Attached the log. Thank you.
[cwltool.log](https://github.com/ncbi/pgap/files/4457931/cwltool.log)

**Comment by azat-badretdin** [comment] 2020-04-09 19:03
Same problem in that one as well. Faraway, too close :-) I guess. We will look into this

**Comment by whlavina** [comment] 2020-04-10 00:09
The most recent `cwltool.log` you attached doesn't show evidence of the `--no-internet` flag. Did you attach the wrong log file by mistake?

Without the flag, internet access is required (we haven't tested use with proxies). We'll improve the documentation to clarify the consequences (mainly, citation lookups).

We'll continue to investigate, but in the meanwhile, if you have an updated log file, being sure to use `--no-internet`, that would be helpful. Thanks!

**Comment by maojn** [comment] 2020-04-10 15:59
I tried again. Please see attachment. Thank you.
[cwltool.log](https://github.com/ncbi/pgap/files/4462299/cwltool.log)

**Comment by azat-badretdin** [comment] 2020-04-10 16:09
Could you please run it with `pgap.py -d` option?

**Comment by maojn** [comment] 2020-04-10 17:49
no problem. Please see attachment.
[cwltool.log](https://github.com/ncbi/pgap/files/4462736/cwltool.log)

**Comment by maojn** [comment] 2020-04-10 17:56
btw, our cluster has proxy setting to connect to internet. I attached the env variables here in case you need it.
$ env | grep -i proxy                                                                              
http_proxy=http://dtn07-e0:3128
ftp_proxy=http://dtn07-e0:3128
RSYNC_PROXY=dtn07-e0:3128
https_proxy=http://dtn07-e0:3128

**Comment by azat-badretdin** [comment] 2020-04-14 21:47
It says Keyboard Interrupt in the end which means that you interrupted it very early. Could you please run it uninterrupted?  After that could you please attach output of `/bin/ls -ltr .`?

Also, I do not see your system parameters posted. Could you please post them?

Thanks!

**Comment by maojn** [comment] 2020-04-15 13:59
Sorry for the mistake. I forgot to change ulimit so stopped and rerun and sent you wrong output file. I have attached the correct output files after rerun with -d. Also the environment variables. I use 20g of memory to run the job. Thank you.

Here is the output:
$ /bin/ls -ltr
total 188
-rw-rw-r-- 1 maoj staff    811 Mar 30 18:32 submol.yaml.gz
-rw-rw-r-- 1 maoj staff 166893 Mar 30 18:32 ASM2732v1.annotation.nucleotide.1.fasta.gz
drwxr-xr-x 5 maoj staff   4096 Apr 15 09:35 debug
-rw-r--r-- 1 maoj staff   8523 Apr 15 09:36 cwltool.log.gz


[envout.txt](https://github.com/ncbi/pgap/files/4481612/envout.txt)
[outfile.zip](https://github.com/ncbi/pgap/files/4481579/outfile.zip)

**Comment by azat-badretdin** [comment] 2020-04-15 14:22
Thanks!

**Comment by whlavina** [comment] 2020-04-15 18:50
The most recent run seems to be missing `--no-internet`; we already discussed that issue, noting we haven't tried supporting proxies (not to mention throttling internet requests across massive compute farms.) That's the reason for the most recent failure.

Of note, we have not been targeting or testing platforms with such high core counts. The software should be efficient for 8 CPU, with diminishing returns up to about 24 CPU, but beyond that level, we know there are limitations and expect poor performance. We have not tested on platforms with 54 to 72 CPU.

We will clarify this in our documentation.

I proceeded to test our software with up to 96 vCPU using Singularity, in a Cloud environment, with appropriate `ulimit` settings (similar to yours, once adjusted) and `--no-internet`. I had repeated success. This suggests your failures (after correcting `--no-internet`) are due to some other cause.

We don't have much experience with Singularity. Your `envout.txt` log shows `SLURM_JOB_CPUS_PER_NODE=4` while the `cwltool.log` shows the process inside Singularity sees `"CPU cores": 56`. Is it possible to lower the number of CPU cores as reported within the Singularity job? With Docker, this is a command line option: `--cpus N`, supported by `pgap.py`; with Singularity, I don't know how this is configured, perhaps by config file somewhere.

One hypothesis, from my compute cluster / batch system experience, is that the cluster may be terminating jobs that significantly exceed their requested resources, e.g. requesting 4 CPU but using 56. That's something to beware.

Could you please rerun again, making sure to include the debug and `--no-internet` flags, and also making sure that `ulimit` meets the minimum recommended values, and reducing CPU if possible? Something like:
`./pgap.py --no-internat -D singularity -r -d -o MG37_results test_genomes-2020-03-30.build4489/MG37/input.yaml`

Then provide once again all the same log files, especially the `debug/tmp-outdir/*/ncbiapp.log` files.

If that doesn't work, I don't know if we have the resources to provide more assistance.

Finally, since this is the NIH Biowulf, if you are internal community, you may wish to reach out to us more directly.

**Comment by maojn** [comment] 2020-04-15 21:32
Sorry I forgot the flag. Here you go:
[outfile2.zip](https://github.com/ncbi/pgap/files/4483808/outfile2.zip)

I am pretty sure the job only used 1 cpu and 2gb maybe and didn't killed by the batch system. I will check if there is a way to specify cpu in singulairty. Thank you.

**Comment by whlavina** [comment] 2020-04-16 12:00
Your latest logs have me scratching my head. I reconfirmed you and I are running the same software release. I see 2 warnings which I haven't seen before. I don't know if they mean anything:
* `[33mWARNING:[0m Bind mount '/scratch => /scratch' overlaps container CWD /scratch/maoj, may not be available`
* `/home/maoj/.bashrc: line 299: /usr/local/etc/slurm/slurm_aliases: No such file or directory`

I cannot explain the errors such as:
```
[2020-04-15 17:25:55] ERROR [step passdata_2] Output is missing expected field file:///pgap/pgap/wf_common.cwl#passdata/asn2pas_xsl
```

This suggests, maybe the reference data is missing or incomplete. I could imagine running out of disk space as an explanation, but the `cwltool.log` shows you have plenty. Let's confirm the reference data is correct - could you try and send back:
```
ls -lR input-2020-03-30.build4489/ test_genomes-2020-03-30.build4489/ 
find input-2020-03-30.build4489/ test_genomes-2020-03-30.build4489/ -type f | xargs md5sum
```

Maybe try that locally, as a SLURM job, and as a SLURM job running inside the Singularity image (reproducing the bind mounts)?

Could it be SLURM / Biowulf remapping of local (submission host) vs target (compute node) network-accessible filesystem paths? Are you running 2 instances of this, in a shared directory?

I'm sorry if we can't help you further.

**Comment by maojn** [comment] 2020-04-16 13:18
Thank you for your reply. I will look into your suggestions. I couldn't
find the instruction regarding singularity part of pgap except the '-D'
flag. Is there a way for me to shell into the container with singularity?
Regards,

Jean

---------- Forwarded message ---------

**Comment by maojn** [comment] 2020-04-16 13:37
Here is the output of 'ls' and 'find'. Thank you.
[lsOutput.txt](https://github.com/ncbi/pgap/files/4487417/lsOutput.txt)
[findOutput.txt](https://github.com/ncbi/pgap/files/4487422/findOutput.txt)

**Comment by whlavina** [comment] 2020-04-17 02:30
Your `input-2020-03-30.build4489` seems to be missing a _lot_ of files, about half (you have 177 of 349), the absences being sprinkled all over plus some big chunks. I'm don't know how that could have happened.

I recommend reinstalling fresh (maybe keeping only the `pgap.py` file) - that is, wiping or moving aside the `VERSION`, `input`, `input-2020-03-30.build4489`, `test_genomes`, and `test_genomes-2020-03-30.build4489` entries and rerunning `./pgap.py --update`.

If you have the space, >30 GB, consider making a backup copy to avoid re-downloading if whatever happened, happens again.

(We did consider checksum verification as a future improvement.)

**Comment by maojn** [comment] 2020-04-17 19:18
OK. Now everything make sense. I got these files based on the instruction from one of our users because I couldn't find instruction for singularity part of pgap. Guess his downloading wasn't good.

# Started over:

$ wget https://github.com/ncbi/pgap/raw/prod/scripts/pgap.py
$ chmod +x pgap.py

# The following is in https://github.com/ncbi/pgap/wiki/Quick-Start, but failed. Nothing downloaded. So I followed what the user did with '-D singularity' flag. Any documentation about this somewhere?
$ ./pgap.py --update  
The latest version of PGAP is 2020-03-30.build4489, you have nothing installed locally.
Docker not found.
# Loaded singularity module and add the -D flag
$ ./pgap.py --update -D singularity
The latest version of PGAP is 2020-03-30.build4489, you have nothing installed locally.
Downloading (as needed) Docker image docker://ncbi/pgap:2020-03-30.build4489
Downloading and extracting tarball: https://s3.amazonaws.com/pgap-data/test_genomes-2020-03-30.build4489.tgz
Downloaded 19693625 of 19693625 bytes (100.00%)

# you mentioned you have 349 files in input-2020-03-30.build4489. But I only have 294 files!!??
$ find /data/maoj/pgap/input-2020-03-30.build4489 -type f | wc -l
294
$ find /data/maoj/pgap/test_genomes-2020-03-30.build4489/ -type f | wc -l
55
$ ls -l
total 975M
drwxr-xr-x 11 maoj staff 4.0K Apr 17 11:46 input-2020-03-30.build4489/
-rwxr-xr-x  1 maoj staff 971M Apr 17 11:38 pgap_2020-03-30.build4489.sif*
-rwxr-xr-x  1 maoj staff  31K Apr 17 11:35 pgap.py*
lrwxrwxrwx  1 maoj staff   33 Apr 17 11:46 test_genomes -> test_genomes-2020-03-30.build4489/
drwxrwxr-x 20 maoj staff 4.0K Apr 17 11:46 test_genomes-2020-03-30.build4489/
-rw-r--r--  1 maoj staff   21 Apr 17 11:46 VERSION

# Allocated an interactive node on biowulf cluster with 30g and 4 cpus 
# please note below that the job use overwhelming number of cpus for some reason
# Our cluster uses cpu based instead of node based allocation
# Is there a way around this?
# Please see the $SLURM_CPUS_PER_TASK in the environment variables attached.
$ sinteractive --mem=30g -cpus-per-task=4

# once on a node, run 'ulimit' to set higher number.
$ ulimit -n 8196

# initiate singularity
$ module load singularity
$ export SINGULARITY_BINDPATH="/data/$USER,/fdb,/scratch,/lscratch"

# Run test
$ ./pgap.py --no-internet -D singularity -r -d -o MG37_results test_genomes-2020-03-30.build4489/MG37/input.yaml
--no-internet flag enabled, not checking remote versions.
Output will be placed in: /spin1/users/maoj/pgap/MG37_results
WARNING: Bind mount '/data/maoj => /data/maoj' overlaps container CWD /data/maoj/pgap, may not be available
PGAP completed successfully.

What worries me most is the cpu usage (as high as 142 cpus even though I only allocated 4cpus).
The app is running on a shared system. How do I run it on say 4 cpus instead of 100cpus? I have attached the cpu/memory usage of the above test job and my environment. 

Thank you for all your help!

![2020-04-17_14-48-03](https://user-images.githubusercontent.com/898043/79603660-c5430e80-80ba-11ea-8021-b754161e8dd9.png)
[envlist.txt](https://github.com/ncbi/pgap/files/4494715/envlist.txt)

**Comment by whlavina** [comment] 2020-04-17 20:16
Great that it's running!

Unfortunately, I don't know Biowulf and Singularity regarding how to make the container see only a limited number of CPU and operate more collaboratively with your compute cluster. The PGAP software inside the container is currently written to assume it can use all available CPU, and that if there are any restrictions on the number of CPUs to use, those are configured at the level of Docker... or in your case, Singularity. We could push the configuration of CPUs down into the CWL, but that would require development effort and isn't among our immediate priorities.

Hopefully, you can find a solution among the rest of the community, but this is beyond where we can help. Do you mind if we close this ticket?

**Comment by maojn** [comment] 2020-04-17 20:41
I see. Please go ahead close the ticket. Thank you!

**Closed** 2020-04-17 21:02 UTC
Labels: PGAPX-762

**Comment by jotes35** [comment] 2020-10-18 01:33
Hi @azat-badretdin 

I tried your approach but bash says operation not permitted. Please advice
