### ISSUE TITLE
unexpected format foundin file: itr_0.lstterminate called after throwing an instance of 'ncbi::CException'[BUG] <title>

### ISSUE THREAD

**Issue by aini-bio** [ncbi/pgap#121] opened 2021-01-29 08:01 UTC
**Describe the bug**
Trying to annotate a nucleotide  sequence  using pgap.
An GENEMARK(CException::eUnknown) occurred.
I am new to the process, therefore I can't completely understand the whole reason for this error. So I am pasting the stack traces below.

```
execing: /tmp/aafbu4in/stg8d5107b0-93c4-4d95-b7d9-69e7ba67c0a5/GeneMark/API_2.2/gmsn.pl --prok --ncbi --gcode 11 --ext genemark-input.gff --incomplete_at_gaps 10 fasta.fna
error, unexpected format foundin file: itr_0.lstterminate called after throwing an instance of 'ncbi::CException'
  what():  NCBI C++ Exception:
    Error: GENEMARK(CException::eUnknown) "../../../../../../../ncbi_cxx/src/internal/gpipe/app/bacterial_pipeline/genemark/genemark.cpp", line 546: {anonymous}::COldGenemarkApplication::Run() --- gmsn.pl call failed: /tmp/aafbu4in/stg8d5107b0-93c4-4d95-b7d9-69e7ba67c0a5/GeneMark/API_2.2/gmsn.pl --prok --ncbi --gcode 11 --ext genemark-input.gff --incomplete_at_gaps 10 fasta.fna
     Stack trace:
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2021-01-11.build5132/arch/x86_64/bin/genemark :0  offset=0x0 addr=0x41e3fc
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2021-01-11.build5132/arch/x86_64/lib/libxncbi.so ../../../ncbi_cxx/src/corelib/ncbiapp.cpp:700 ncbi::CNcbiApplicationAPI::x_TryMain(ncbi::EAppDiagStream, char const*, int*, bool*) offset=0x0 addr=0x7f7c01ff2d62
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2021-01-11.build5132/arch/x86_64/lib/libxncbi.so ../../../ncbi_cxx/src/corelib/ncbiapp.cpp:978 ncbi::CNcbiApplicationAPI::AppMain(int, char const* const*, char const* const*, ncbi::EAppDiagStream, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) offset=0x0 addr=0x7f7c01ff5014
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2021-01-11.build5132/arch/x86_64/bin/genemark :0  offset=0x0 addr=0x4155c5
      /usr/lib64/libc-2.17.so :0  offset=0x0 addr=0x7f7bff253554
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2021-01-11.build5132/arch/x86_64/bin/genemark :0  offset=0x0 addr=0x415849
       :0  offset=0x0 addr=0xffffffffffffffff

Stack trace (most recent call last):
#12   Object "", at 0xffffffffffffffff, in
#11   Object "/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2021-01-11.build5132/arch/x86_64/bin/genemark", at 0x415849, in _start
#10   Object "/usr/lib64/libc-2.17.so", at 0x7f7bff253554, in __libc_start_main
#9    Object "/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2021-01-11.build5132/arch/x86_64/bin/genemark", at 0x4155c5, in main
#8    Source "../../../ncbi_cxx/src/corelib/ncbiapp.cpp", line 978, in AppMain [0x7f7c01ff5014]
#7    Source "../../../ncbi_cxx/src/corelib/ncbiapp.cpp", line 700, in x_TryMain [0x7f7c01ff2d62]
#6    Object "/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2021-01-11.build5132/arch/x86_64/bin/genemark", at 0x41e4af, in _start
#5    Source "../../../../gcc-7.3.0/libstdc++-v3/libsupc++/eh_throw.cc", line 93, in __cxa_throw [0x7f7bffdd5262]
#4    Source "../../../../gcc-7.3.0/libstdc++-v3/libsupc++/eh_terminate.cc", line 57, in terminate [0x7f7bffdd5020]
#3    Source "../../../../gcc-7.3.0/libstdc++-v3/libsupc++/eh_terminate.cc", line 47, in __cxa_begin_catch [0x7f7bffdd4fd5]
#2    Source "../../../../gcc-7.3.0/libstdc++-v3/libsupc++/vterminate.cc", line 95, in __verbose_terminate_handler [0x7f7bffdd71e4]
#1    Object "/usr/lib64/libc-2.17.so", at 0x7f7bff268a77, in abort
#0    Object "/usr/lib64/libc-2.17.so", at 0x7f7bff267387, in raise
Aborted (Signal sent by tkill() 1107 0)

```
**To Reproduce**
python pgap.py -r -o <output_dir> input.txt

**Software versions (please complete the following information):**
 - OS: Windows 10, PowerShell as Administrator
 - Python: Python 3.7.0

 - pgap.py --version:    PGAP version 2021-01-11.build5132
 - Docker: Docker version 20.10.2, build 2291f61

**Log Files**
Re-executed the pgap.py with the ``--debug`` flag and attached an archive of the logs in the directory: ``debug/tmp-outdir/*/*.log`` below.
[tmp-outdir.zip](https://github.com/ncbi/pgap/files/5892417/tmp-outdir.zip)

**Comment by azat-badretdin** [comment] 2021-01-29 10:39
Thank you for your report! We appreciate that you provided enough data to start tackling this issue.

**Comment by azat-badretdin** [comment] 2021-01-29 11:05
Given the input you uploaded to the command that produced the data file `itr_0.lst` I was not able to reproduce this (shortened) file. 

I suspect that some kind of memory limitations were in place. I do not think it's file system space problem, which leaves the memory as a potential culprit.

Could you please post the System characteristics of your Windows machine and memory settings for docker?

Thanks

**Comment by aini-bio** [comment] 2021-02-01 07:14
Thank you for prompt response.
My System specifications are given below:

Processor: Intel Core i7-9700 (3Ghz)
RAM: 32 GB
OS: Windows 10 (64 Bit)
HDD: 162 GB Free Space
I have 1TB free space on another drive.

Docker: 
I am new to docker but I believe you are asking about the memory usage of docker image, that is 7.99 GB/ 7.99 GB used. as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/78193785/106425978-1d130080-64a8-11eb-9dd3-81d7749c276b.png)

If it is the allocated memory issue then please guide me how to increase the allocated memory, or how to allocate memory in a different hard drive.

Thanks a lot.

**Comment by azat-badretdin** [comment] 2021-02-01 11:05
Thanks! We tracked this issue to third party application problem which will be resolved in the next release (we already had the version, but we did not have time to squeeze it into the last release).

**Comment by azat-badretdin** [comment] 2021-02-01 18:41
Actually, in this particular case, it's more complex, since I was not able to reproduce this error with exactly the same input. This could be related to Windows/Docker peculiarities.

**Comment by azat-badretdin** [comment] 2021-02-08 19:37
It's not clear now what happens in this particular Windows/Docker use case. Alas, we are not able to meaningfully contribute here.

**Closed by azat-badretdin** 2021-02-08 19:37 UTC
Labels: PGAP-4166, PGAPX-886
