### ISSUE TITLE
PGAP failed, docker exited with rc = 1 when running mycoplasma genitalium test file

### ISSUE THREAD

**Issue by paulowensmith** [ncbi/pgap#104] opened 2020-10-16 17:11 UTC
Using Windows 10, newest version of Docker Desktop, newest version of PGAP (build4894)

I run this command in Command Prompt:

 .\pgap.py -r -o mg37_results test_genomes/MG37/input.yaml

Docker container starts up and runs for a while and then ends after 20min or so with "WARNING Final process status is permanentFail"

I'm fairly new to this so I'm not sure where I might be going wrong. I've attached the cwltool text file in the mg37_results folder 
that is generated, seems like it contains a log of what happened.

[cwltool.log](https://github.com/ncbi/pgap/files/5393238/cwltool.log)

Thanks!

**Comment by azat-badretdin** [comment] 2020-10-16 18:50
Could you please provide your W10 system parameters (memory, disk space on the disk you used)?

The error originates in original 3rd party GeneMark executable:

```error, unexpected format found in file: itr_0.lst```

**Comment by paulowensmith** [comment] 2020-10-16 19:17
I am running on:
Microsoft Windows 10 pro 10.0.19041 Build 19041 x64
Intel Core i7-5500U CPU @ 2.4GHz - 2 cores 4 threads
12.4GB available memory (RAM), 16GB installed, with another 22GB of available virtual memory
368GB free space on Local Disk (C:)

Which matches up with the info in the start of the cwltool file under Runtime Report. It seems like the computer has the specs required, and I checked and made sure it had SSE 4.2 support.

Couldn't find any files labeled itr_0.lst when searching the local disk. Is it one of the files downloaded with the supplementary reference data or CWL code?

Thank you for your help.

**Comment by azat-badretdin** [comment] 2020-10-16 20:01
> Is it one of the files downloaded with the supplementary reference data or CWL code?

No. It's one of the files generated by 3rd party GeneMark application. We located a similar problem with a different input in classic PGAP. So far it is not clear how they are related. We are investigating.

**Comment by jotes35** [comment] 2020-10-19 13:56
Hi All,

I had a similar error message (docker exited with rc=1). What baffles me is the test_genomes/MG37/input.yaml executed properly. But the error comes when I am running my data.
This is the error message 

PGAP version 2020-09-24.build4894 is up to date.
Output will be placed in: /home/user/researchPA40annot
INFO:    Using cached SIF image
PGAP failed, docker exited with rc = 1
Unable to find error in log file.


Attached is the cwl log
[cwltool.log](https://github.com/ncbi/pgap/files/5402279/cwltool.log)

**Comment by azat-badretdin** [comment] 2020-10-19 14:02
Thanks! If your data is sharable feel free to post it, so we can use it for testing in classic PGAP ticket.

**Comment by azat-badretdin** [comment] 2020-10-19 14:41
I was pointed to the fact that cwltool.log you posted has this:

```[2020-10-19 13:31:22] ERROR Tool definition failed validation:
user_input/pgap_input.yaml:2:10: mapping values are not allowed here
```

Which indicates to some YAML problem with your file. If you can't figure out what it is, feel free to post it here, we'll have a look

**Comment by thibaudnis** [comment] 2020-10-19 14:44
@jotes35  Please see https://github.com/ncbi/pgap/wiki/Input-Files for information to include in the yaml files.

**Comment by jotes35** [comment] 2020-10-19 15:41
These are my yaml files. I added .txt for fit the github format


[input.yaml.txt](https://github.com/ncbi/pgap/files/5403027/input.yaml.txt)
[submol.yaml.txt](https://github.com/ncbi/pgap/files/5403028/submol.yaml.txt)

**Comment by azat-badretdin** [comment] 2020-10-19 15:58
Your input file `input.yaml`:

```fasta
    class: File
    location: PA40a.fasta
submol
    class: File
    location: submol.yaml```

lacks colons after `fasta` and `submol` lines

**Comment by jotes35** [comment] 2020-10-19 17:16
Thanks @azat-badretdin 

Its running now.

**Comment by jotes35** [comment] 2020-10-23 23:38
Hi @azat-badretdin I submitted another issue [here](https://github.com/ncbi/pgap/issues/107)

I will grateful if you can advise on what to do   Thanks

**Comment by paulowensmith** [comment] 2020-11-09 17:22
Hi Azat, is there any resolution or further information on the genemark executable problem I had?

**Comment by azat-badretdin** [comment] 2020-11-09 18:55
Not sure I understand. You said: ```Its running now.``` which felt final. How did that run finish? Did you reproduce the same problem?

**Comment by paulowensmith** [comment] 2020-11-09 18:59
Hi Azat, the "it's running now" was another user who jumped into the thread to report a different problem. I still have the original problem, failure with the genemark executable

**Comment by azat-badretdin** [comment] 2020-11-09 19:03
I apologize, it seems like I got distracted by an unrelated issue addressed in this ticket

**Comment by paulowensmith** [comment] 2020-11-09 19:06
Not a problem, I'll try a reinstall again this week to see if the problem persists. It's been a while since I've tried to troubleshoot it.

**Comment by azat-badretdin** [comment] 2020-11-09 19:10
Thanks! Surely, that could be helpful. I opened internal ticket for this, so we track this better. 

This might be a Windows 10 specific issue which might take some time to resolve since we are completely new to running our docker under windows.

**Closed** 2021-01-04 15:12 UTC
Labels: PGAPX-860

**Comment by Subhajeet1997** [comment] 2021-05-03 14:45
i am running pgap for the first time. i have run pgap on the sample file successfully. But when i run on my data its showing error. 
I have used the following command :
sudo python3 pgap.py -D /usr/bin/docker -n -o lk_bacteria_pgap_result lk_bacteria/input.yaml --no-internet 

then it gives a huge error which is in the following cwltool.log file.
[cwltool.log](https://github.com/ncbi/pgap/files/6415559/cwltool.log)

can anyone help me fixing this? i have no clue about this.

thanks,

**Comment by azat-badretdin** [comment] 2021-05-03 15:13
The problem here is different, would you mind opening a separate issue for this?

**Comment by azat-badretdin** [comment] 2021-05-04 22:20
Please provide as much data as possible. Another advice is to run it with `pgap.py -d` option, this will produce some useful additional files handy for post portems.

**Comment by azat-badretdin** [comment] 2021-05-04 22:43
Also, there might be some XML files in the output directory. Feel free to examine them on clues or post them in the new ticket.

**Comment by Subhajeet1997** [comment] 2021-05-05 06:33
okay i will try by this pgap.py -d .

**Comment by Subhajeet1997** [comment] 2021-05-05 07:34
i have run the following command :
sudo ./pgap.py -D /usr/bin/docker  -n -o lk_bacteria_pgap_result lk_bacteria/input.yaml -d
i got the same type of error
[cwltool.log](https://github.com/ncbi/pgap/files/6425560/cwltool.log)

Failer nodes:
<?xml version="1.0" encoding="UTF-8"?>
<message severity="ERROR" seq-id="lcl|ctg1" code="SEQ_FEAT_BadCharInAuthorName">Bad characters in author ?</message>

<?xml version="1.0" encoding="UTF-8"?>
<message severity="ERROR" seq-id="lcl|ctg2" code="SEQ_FEAT_BadCharInAuthorName">Bad characters in author ?</message>

<?xml version="1.0" encoding="UTF-8"?>
<message severity="ERROR" seq-id="lcl|ctg3" code="SEQ_FEAT_BadCharInAuthorName">Bad characters in author ?</message>

<?xml version="1.0" encoding="UTF-8"?>
<message severity="ERROR" seq-id="lcl|ctg4" code="SEQ_FEAT_BadCharInAuthorName">Bad characters in author ?</message>

**Comment by azat-badretdin** [comment] 2021-05-05 07:51
Please post your input

**Comment by azat-badretdin** [comment] 2021-05-05 07:53
Also: please have a look at this input file requirement

https://github.com/ncbi/pgap/wiki/Input-Files

> Currently the metadata in the submol.yaml file only supports the 7-bit ASCII subset of Unicode. We are working on supporting the full UTF-8 character set.

If you have extended ASCII characters in authors' names, please remove them
