### ISSUE TITLE
annotation running time

### ISSUE THREAD

**Issue by Mayankguptai** [ncbi/pgap#30] opened 2019-08-14 08:09 UTC
Hey,

How long it generally takes to annotate E. coli. genome?
It's been more than 24hrs and only single CPU is occupied by the run.
I have 88 CPU server with 512 GB RAM Centos 7. PGAP version 2019-08-01.build3919

Thanks
Mayank

**Comment by azat-badretdin** [comment] 2019-08-14 10:32
Thank you for your report! I presume you have more than one CPU... Could you please post 

- Command line
- Output of command `tail cwltool.log `(use `find . -name cwltool.log ` if it's not in current directory)
- Output of command  `grep -P '2019.*\[.*\].*\$' cwltool.log | tail`
- Output of command `head cwltool.log`

We will take a look at this at earliest opportunity!

**Comment by azat-badretdin** [comment] 2019-08-15 12:11
Could you please check if while your run is running, you already have results in the directory specified in `-o dir` parameter?

**Comment by Mayankguptai** [comment] 2019-08-15 17:11
Now I am running for the test genome. 

1. command  used 
`./pgap.py -r -o mg37_results test_genomes/MG37/input.yaml `

Attaching cwltool.log file for this run.
[cwltool.log](https://github.com/ncbi/pgap/files/3506490/cwltool.log)

**Comment by Mayankguptai** [comment] 2019-08-15 17:22
On a different server test run got completed but when I tried to run pgap.py on our own data, linear genome (partial,  having multiple contig sequences), it died after some time.

Here is cwltool.log file for this run.
[P2_cwltool.log](https://github.com/ncbi/pgap/files/3506524/P2_cwltool.log)

**Comment by azat-badretdin** [comment] 2019-08-15 18:16
P2_cwltool.log fails in the `screen_evaluate` stage. Probably because you have some contamination:

```
[2019-08-15 16:42:28] INFO [job screen_evaluate] /tmp/xb6uy47p$ screen_evaluate \
    -asn \
    /tmp/tmp2xcb77ma/stgdf25e4f4-9358-48d5-87b5-4422833683e9/feats.asn \
    -ifmt \
    seq-annot \
    -tab \
    /tmp/tmp2xcb77ma/stg3022c44c-2497-4476-b5ff-99b0f1b1c8d3/calls.tab
[2019-08-15 16:42:29] INFO Could not collect memory usage, job ended before monitoring began.
[2019-08-15 16:42:29] WARNING [job screen_evaluate] completed permanentFail

```

Please see if any of feats.asn or calls.tab are non-empty

**Comment by azat-badretdin** [comment] 2019-08-15 18:18
> Attaching cwltool.log file for this run.

That one ended quite abruptly, hard to say what happened.

**Comment by tseemann** [comment] 2019-08-16 00:15
I believe `cwl-runner` can only run 1 process at a time ?

**Comment by Mayankguptai** [comment] 2019-08-16 08:40
> 
> 
> P2_cwltool.log fails in the `screen_evaluate` stage. Probably because you have some contamination:
> 
> ```
> [2019-08-15 16:42:28] INFO [job screen_evaluate] /tmp/xb6uy47p$ screen_evaluate \
>     -asn \
>     /tmp/tmp2xcb77ma/stgdf25e4f4-9358-48d5-87b5-4422833683e9/feats.asn \
>     -ifmt \
>     seq-annot \
>     -tab \
>     /tmp/tmp2xcb77ma/stg3022c44c-2497-4476-b5ff-99b0f1b1c8d3/calls.tab
> [2019-08-15 16:42:29] INFO Could not collect memory usage, job ended before monitoring began.
> [2019-08-15 16:42:29] WARNING [job screen_evaluate] completed permanentFail
> ```
> 
> Please see if any of feats.asn or calls.tab are non-empty
How can I track it?
These files are temporary.

**Comment by Mayankguptai** [comment] 2019-08-16 08:46
> 
> 
> P2_cwltool.log fails in the `screen_evaluate` stage. Probably because you have some contamination:
> 
> ```
> [2019-08-15 16:42:28] INFO [job screen_evaluate] /tmp/xb6uy47p$ screen_evaluate \
>     -asn \
>     /tmp/tmp2xcb77ma/stgdf25e4f4-9358-48d5-87b5-4422833683e9/feats.asn \
>     -ifmt \
>     seq-annot \
>     -tab \
>     /tmp/tmp2xcb77ma/stg3022c44c-2497-4476-b5ff-99b0f1b1c8d3/calls.tab
> [2019-08-15 16:42:29] INFO Could not collect memory usage, job ended before monitoring began.
> [2019-08-15 16:42:29] WARNING [job screen_evaluate] completed permanentFail
> ```
> 
> Please see if any of feats.asn or calls.tab are non-empty

How can I track it?
These files are temporary. Any suggestion?

**Comment by azat-badretdin** [comment] 2019-08-16 10:25
>I believe cwl-runner can only run 1 process at a time ?

@tseemann 

`cwltool` can run only one process at a time, that is correct. But vast majority of CPU a typical PGAPX run is consumed by two hefty `blastp` executions that try to utilize all CPUs of the multi-core host, so in terms of multi-tasking individual nodes of CWL we are not losing much time. 

> These files are temporary. Any suggestion?

@Mayankguptai 

Running with `./pgap.py --debug` option should guarantee that these files are left under current directory.  Could you please try that?

**Comment by Mayankguptai** [comment] 2019-08-16 12:08
> 
> 
> > P2_cwltool.log fails in the `screen_evaluate` stage. Probably because you have some contamination:
> > ```
> > [2019-08-15 16:42:28] INFO [job screen_evaluate] /tmp/xb6uy47p$ screen_evaluate \
> >     -asn \
> >     /tmp/tmp2xcb77ma/stgdf25e4f4-9358-48d5-87b5-4422833683e9/feats.asn \
> >     -ifmt \
> >     seq-annot \
> >     -tab \
> >     /tmp/tmp2xcb77ma/stg3022c44c-2497-4476-b5ff-99b0f1b1c8d3/calls.tab
> > [2019-08-15 16:42:29] INFO Could not collect memory usage, job ended before monitoring began.
> > [2019-08-15 16:42:29] WARNING [job screen_evaluate] completed permanentFail
> > ```
> > 
> > 
> > Please see if any of feats.asn or calls.tab are non-empty
> 
> How can I track it?
> These files are temporary. Any suggestion?

After screening I found some of the sequences hit with adaptors, I guess this is the reason for contamination.

**Comment by azat-badretdin** [comment] 2019-08-16 12:13
1/ case

>After screening I found some of the sequences hit with adaptors, I guess this is the reason for contamination.

Note that we are doing here an unnecessary check for `feats.asn` which actually filters into `calls.tab` in only essential hits. False positives are possible. The fix for that is in `origin/dev` and it will be included into the next release. 

2/ case P2_cwltool.log

Did you try to reproduce this? If you are planning to, try it with `--debug` flag and see what is happening.

**Comment by Mayankguptai** [comment] 2019-08-16 14:37
> 
> 
> 1/ case
> 
> > After screening I found some of the sequences hit with adaptors, I guess this is the reason for contamination.
> 
> Note that we are doing here an unnecessary check for `feats.asn` which actually filters into `calls.tab` in only essential hits. Thus, in current release code, False positives are possible. The fix for that is in `origin/dev` and it will be included into the next release.
> 
> 2/ case P2_cwltool.log
> 
> Did you try to reproduce this? If you are planning to, try it with `--debug` flag and see what is happening.

Yeah, calls.tab is non-empty.

`cat ./tmp-outdir/0t7c9d44/calls.tab`
lcl|contig_4    M       185239..185265  adaptor:NGB01088.1      Adaptor
lcl|contig_5    M       134536..134562  adaptor:NGB01088.1      Adaptor
lcl|contig_6    M       39085..39117    adaptor:NGB01096.1      Adaptor
lcl|contig_17   M       5349..5387      adaptor:NGB00860.1      Adaptor

**Comment by azat-badretdin** [comment] 2019-08-16 14:41
> Yeah, calls.tab is non-empty.

Cool :-)

Any developments on case P2_cwltool.log?

**Comment by Mayankguptai** [comment] 2019-08-17 08:02
> Any developments on case P2_cwltool.log?
After I edited these contigs, now the task is done.

**Comment by Mayankguptai** [comment] 2019-08-17 08:02
After I edited these contigs, now the task is done.

**Comment by Mayankguptai** [comment] 2019-08-17 08:05
After I edited these contigs, now the task is done.

**Closed** 2019-08-19 10:35 UTC
