### ISSUE TITLE
[FEATURE REQUEST] ARM64 support

### ISSUE THREAD

**Issue by rjavier17** [ncbi/pgap#265] opened 2023-07-19 14:03 UTC
**Is your feature request related to a problem? Please describe.**
Currently it is impossible to run PGAP under an ARM64 processor (Apple Silicon/M1/M2, for instance, but also Linux ARM64 distributions). 

**Describe the solution you'd like**
Native PGAP version for these architectures, a docker container or at least Conda/Anaconda option. 

**Describe alternatives you've considered**
Tried to run PGAP in Docker, and using Rosetta compatibility, and also Virtual machines (Virtuabox, QEMU, Parallels...). It did not work. 

**Additional context**
These architectures are becoming more and more popular, and it is a matter of time every MacOSX user will have upgraded their devices to a ARM64 based computer.

**Comment by azat-badretdin** [comment] 2023-07-19 15:01
Thank you for your report, @rjavier17 we will look at this issue at the earliest opportunity!

**Comment by george-coulouris** [comment] 2023-08-15 14:01
duplicate of https://github.com/ncbi/pgap/issues/166

**Closed as not planned** 2023-08-15 14:02 UTC
